### PR TITLE
Add exclude option to enable certain properties to be excluded from being reset

### PR DESCRIPTION
**Pull request by gcazaciuc**

### CODE REVIEW

**Comment by kof** [comment]
When would you need that?

**Comment by kof** [comment]
you can simply pass in `reset` option props with 'inherited' as a value if you want them to be inherited from the parents.

**Comment by gcazaciuc** [comment]
ideally i would like to have inheritance from the parent  selectors within the same stylesheet but not from outside the component styles. However i'm not entirely sure how to achieve that. in the mean time i thought it might be beneficial at least to have an option to disable some resets in order to not code over and over again the same declarations within the same component file but instead have them declared once on the component root and inherit them in other selectors within the same comp at least more common styles like font family. Didn't thought about using reset that way.

**Comment by kof** [comment]
What you did is just another option to globally define props to not to get reseted. This is not what you are asking for at all.

**Comment by kof** [comment]
Thats why you should always explain what you want to achieve first.

**Comment by kof** [comment]
I also think most of the time you don't want inheritance even inside of one component. However you can define something for all paragrphs or divs by using jss-nested.

**Comment by gcazaciuc** [comment]
Thanks, makes sense

**Pull request closed without merging**
